.run_on_merge_request:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_COMMIT_TITLE =~ /chore\(version\)\:.*/'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: on_success

.run_on_main:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_COMMIT_TITLE =~ /chore\(version\)\:.*/'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: on_success

.cache-x86-64:
  cache:
    key: x86-64
    paths:
      - target/

stages:
  - container-x86-64
  - container-flatpak
  - prechecks
  - checks
  - release
  - post-release

# Building manjro-base docker images on gitlab does not work currently.
# include:
#   - local: /ci/.gitlab-ci-containers.yml


formatting & clippy:
  image: registry.gitlab.com/floers/cargo-gra/public-x86-64:main
  stage: prechecks
  extends: [.run_on_merge_request]
  cache:
    key: x86-64-clippy
    paths:
      - target/
  script:
    - source $HOME/.cargo/env
    - cargo fmt --all -- --color=always --check
    - cargo clippy --no-deps --features ui,store

outdated & audit:
  image: registry.gitlab.com/floers/cargo-gra/public-x86-64:main
  allow_failure: true
  stage: prechecks
  extends: [.run_on_merge_request]
  script:
    - source $HOME/.cargo/env
    - cargo outdated -R
    - cargo audit
    - cargo outdated -R --exit-code 1

build and test x86-64:
  image: registry.gitlab.com/floers/cargo-gra/public-x86-64:main
  stage: checks
  extends: [.run_on_merge_request, .cache-x86-64]
  script:
    - source $HOME/.cargo/env
    - cargo test --release
    - cd examples/simple && cargo gra gen && cargo build --release && cd ../..

release:
  image: registry.gitlab.com/floers/cargo-gra/public-x86-64:main
  stage: release
  extends: [.run_on_main, .cache-x86-64]
  script:
    - source $HOME/.cargo/env
    - REMOTE=1 ci/release.sh

update dependency cache:
  image: registry.gitlab.com/floers/cargo-gra/public-x86-64:main
  stage: post-release
  extends: [.cache-x86-64]
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never
  script:
    - source $HOME/.cargo/env
    - cargo clean
    - cargo build --release

released:
  image: registry.gitlab.com/floers/cargo-gra/public-x86-64:main
  stage: post-release
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /chore\(version\):.*/
  script:
    - echo "Everything is fine"
