[package]
name = "gtk-app-framework"
version = "0.0.1"
edition = "2018"

[dependencies]
log = "0.4"
gettext-rs = "0.7"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
serde-xml-rs = "0.5"