[package]
name = "gtk-rust-app"
version = "0.0.1"
edition = "2018"

[features]
default = [ "store" ]
build = []
store = [ "gstore" ]

[dependencies]
log = "0.4"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
serde_json = "1"
gettext-rs = "0.7"
gstore = { path = "../gstore", optional = true }
# gstore = { git = "https://gitlab.com/loers/gstore.git" }
gtk = { version = "0.3", package = "gtk4" }
gdk4 = "0.3"
glib = "0.14"
libadwaita = "0.1.0-alpha-6"
