post_bump_hooks = []
pre_bump_hooks = [
  """
    sh -c "./ci/update_dependency.sh gtk-rust-app-derive {{latest}} {{version}}"
    """,
  "cargo bump {{version}}",
  "cargo update",
]
tag_prefix = "v"

[commit_types]

[changelog]
authors = []
path = "CHANGELOG.md"

[bump_profiles]
